### ISSUE TITLE
The specific info about these variants?

### ISSUE THREAD

**Issue by hooke007** [AN3223/dotfiles#4]
More shaders have been added, could you please share more info about the nlmeans shaders' variants?

**Comment by AN3223** [comment]
Hi! I just pushed a commit adding descriptions to each variant, 563130e6fb933073a65b89434451787baa57560d. If you have any other questions please let me know.

**Comment by AN3223** [comment]
Anime is usually much simpler than general content (high contrast, very
little textural detail), so it can be denoised much more aggressively (high
denoising factor, high RF) while incurring less noticeable blur. The
WIDTH/HEIGHT difference is related to RF, which looks good on anime IMO.

The temporal shaders are currently the only ones requiring vo=gpu-next,
since vo=gpu doesn't have any way to access previous frames. I'll add this
to the profile descriptions, and I'll be sure to document this better in
the future too.

The anime profiles (and many others) are very new, so I am especially
interested in feedback and suggestions on them, big or small! As well as
any other feedback and suggestions you may have :)

**Comment by hooke007** [comment]
gpu-next support changing shader's internal variables on the fly, you may not need to generate many variants for `temporal` :)

**Comment by AN3223** [comment]
Wow thanks for showing me this! I'm not sure if it's useful for temporal
since temporal currently requires code generation, but I can see this being
useful for a lot of things.

**Comment by hooke007** [comment]
I also notice that the differnet variants use the same `//!DESC`. Probably add the variant' name would be better.

**Comment by AN3223** [comment]
Thanks, just pushed a commit that appends the filename to DESC.

**Comment by hooke007** [comment]
Hi, I noticed that the recent commit make all shaders use the same desc name.

**Comment by AN3223** [comment]
Hi, the description names seem to be intact, for example:

https://github.com/AN3223/dotfiles/blob/5be8b7c6cc23da55c068a347de9303b8d54551cf/.config/mpv/shaders/nlmeans_temporal.glsl#L292

However I did start injecting Guided Filter into the NLM shaders for better
quality, and as a side effect there are a lot of shader stages now. This
pushes the main shader stage (with the filename in the desc) to the bottom
in the UI, so you may have to scroll down to see it depending on how much
text fits into your mpv window.

Sorry if this is an inconvenience!
