### ISSUE TITLE
Denoise shaders for anime 

### ISSUE THREAD

**Issue by Zabooby** [AN3223/dotfiles#8]
Are the nlmeans shaders geared towards live action media? 

If they are, would you be interested in making denoisers specifically for anime, something like the [Anime4k shaders](https://github.com/bloc97/Anime4K/wiki/Denoise-Shaders) but better?

**Comment by AN3223** [comment]
There were anime variants of the nlmeans shaders, but over time the anime-specific features worked their way into the general profile and they eventually converged. So the current general profile is effectively the anime profile + all of the advancements since then. I regularly test against anime, both in synthetic benchmarks and with my eyeballs, and I'm open to creating an anime profile if it is discovered that advancements can be made there. But right now I don't have any ideas on how to specifically improve quality on anime.

NLM can be used in conjunction with Anime4k, just run NLM and don't run the Anime4k denoisers. (NLM and Anime4k hook into different planes so NLM will always run first, regardless of the order you specify, probably won't pose an issue though.) I haven't tried this but it should work fine.

Oh also a lot of anime is upscaled before it ever gets to you. So it will be "1080p" but effectively 720p or some other resolution. I open the mpv console (backtick key) and type `vf toggle scale=-2:720` (or whatever resolution seems appropriate) so the shaders can effectively operate on the image (if any detail is lost then you've scaled down too far). Run the `vf toggle` command again (backtick, up arrow, enter) to toggle it off or `vf clr ""` to clear all filters.
